#pragma once

#define WIFI_SSID "YOUR_WIFI_SSID"
#define WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define SERVER_HOSTNAME "192.168.178.2"
#define SERVER_PORT 3000

#ifndef BOARD_NAME
#define BOARD_NAME "ESP32-C3"
#endif